name: Simulator PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  simulator-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.1
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Typecheck (pricing-lib)
        run: pnpm run typecheck:simulator

      - name: Unit tests (pricing-lib)
        run: pnpm run test:simulator:unit

      - name: Integration tests (smoke subset)
        run: pnpm run test:simulator:integration

      - name: Upload coverage (optional)
        if: ${{ always() }}
        run: echo "Coverage upload step placeholder"


